/* ============================================================
 * Atlas Design System · Design Tokens · JS/TS Output
 * 与 CSS 自定义属性逐一对齐 · Version: V1.0.0 · 2026.07
 * Source: 01-前端底层设计.md §13.2
 * ============================================================ */

export const tokens = {
  color: {
    brand: {
      brand1: '#F0F9FF',
      brand2: '#E6F7FF',
      brand3: '#BAE7FF',
      brand4: '#91D5FF',
      brand5: '#69C0FF',
      brand6: '#40A9FF',
      brand7: '#1890FF',
      brand8: '#096DD9',
      brand9: '#0050B3',
      brand10: '#003A8C',
    },
    accent: {
      accent1: '#EEF2FF',
      accent2: '#DCE3FF',
      accent3: '#B9C7FF',
      accent4: '#8FA5FF',
      accent5: '#6A82FF',
      accent6: '#4566FF',
      accent7: '#245BFF',
      accent8: '#1A47D9',
      accent9: '#1238A8',
      accent10: '#0B2470',
    },
    success: {
      success1: '#F6FFED',
      success2: '#B7EB8F',
      success3: '#52C41A',
      success4: '#389E0D',
      success5: '#237804',
    },
    warning: {
      warning1: '#FFFBE6',
      warning2: '#FFE58F',
      warning3: '#FAAD14',
      warning4: '#D48806',
      warning5: '#AD6800',
    },
    error: {
      error1: '#FFF1F0',
      error2: '#FFA39E',
      error3: '#F5222D',
      error4: '#CF1322',
      error5: '#A8071A',
    },
    info: {
      info1: '#E6F7FF',
      info2: '#91D5FF',
      info3: '#1890FF',
      info4: '#096DD9',
      info5: '#0050B3',
    },
    gray: {
      gray1: '#F7F7F8',
      gray2: '#EDEDF0',
      gray3: '#E2E2E7',
      gray4: '#D3D3DA',
      gray5: '#B8B8C1',
      gray6: '#9999A5',
      gray7: '#7A7A86',
      gray8: '#5E5E6A',
      gray9: '#45454F',
      gray10: '#2F2F37',
      gray11: '#1F1F25',
      gray12: '#15151B',
      gray13: '#0E0E13',
      gray14: '#0A0B12',
    },
    read: {
      bgDay: '#FFFFFF',
      bgNight: '#1A1A1A',
      bgSepia: '#F5EDDC',
      bgParchment: '#F4ECD8',
      textDay: '#2A2B33',
      textNight: '#E0E0E0',
      textSepia: '#5B4636',
      textParchment: '#5B4636',
      textSecondaryDay: '#5E5E6A',
      textSecondaryNight: '#888888',
      textSecondarySepia: '#8C7355',
      textSecondaryParchment: '#8C7355',
    },
    semantic: {
      textPrimary: 'var(--gray-14)',
      textSecondary: 'var(--gray-8)',
      textTertiary: 'var(--gray-6)',
      textDisabled: 'var(--gray-5)',
      textInverse: 'var(--gray-1)',
      textLink: 'var(--brand-7)',
      textLinkHover: 'var(--brand-6)',
      bgPage: 'var(--gray-1)',
      bgSurface: '#FFFFFF',
      bgSubtle: 'var(--gray-2)',
      bgElevated: '#FFFFFF',
      bgMask: 'rgba(10, 11, 18, 0.45)',
      borderDefault: 'var(--gray-4)',
      borderSubtle: 'var(--gray-3)',
      borderFocus: 'var(--brand-7)',
      borderStrong: 'var(--gray-6)',
      brand: 'var(--brand-7)',
      brandHover: 'var(--brand-8)',
      brandActive: 'var(--brand-9)',
      brandBg: 'var(--brand-2)',
      brandBorder: 'var(--brand-3)',
      accent: 'var(--accent-7)',
      accentHover: 'var(--accent-8)',
      accentActive: 'var(--accent-9)',
      feedbackSuccess: 'var(--success-3)',
      feedbackSuccessBg: 'var(--success-1)',
      feedbackWarning: 'var(--warning-3)',
      feedbackWarningBg: 'var(--warning-1)',
      feedbackError: 'var(--error-3)',
      feedbackErrorBg: 'var(--error-1)',
      feedbackInfo: 'var(--info-3)',
      feedbackInfoBg: 'var(--info-1)',
    },
  },
  font: {
    sans: "'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', system-ui, -apple-system, sans-serif",
    serif: "'Noto Serif SC', 'Source Han Serif SC', 'Songti SC', serif",
    mono: "'JetBrains Mono', 'SFMono-Regular', Consolas, 'Liberation Mono', monospace",
    size: {
      display: '64px',
      h1: '40px',
      h2: '28px',
      h3: '20px',
      body: '16px',
      caption: '13px',
      overline: '11px',
    },
    weight: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    lineHeight: {
      tight: '1.15',
      normal: '1.5',
      relaxed: '1.7',
    },
  },
  novel: {
    fontFamily: 'var(--font-serif)',
    fontSize: '18px',
    lineHeight: '1.8',
    paragraphSpacing: '1em',
    textColor: 'var(--gray-11)',
    measure: '42ch',
    readBg: 'var(--read-bg-day)',
    readText: 'var(--read-text-day)',
    readTextSecondary: 'var(--read-text-secondary-day)',
  },
  reader: {
    tapZone: '80px',
    tapCenter: '40%',
    toolbarHeight: '56px',
    progressHeight: '3px',
    chapterGap: 'var(--space-12)',
    paragraphIndent: '2em',
    lineSpacingExtra: '0.05em',
  },
  space: {
    space1: '4px',
    space2: '8px',
    space3: '12px',
    space4: '16px',
    space5: '20px',
    space6: '24px',
    space8: '32px',
    space10: '40px',
    space12: '48px',
    space16: '64px',
    space20: '80px',
    space24: '96px',
    space32: '128px',
  },
  radius: {
    none: '0',
    xs: '2px',
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    xxl: '24px',
    full: '9999px',
  },
  shadow: {
    sh1: '0 1px 2px 0 rgba(0, 0, 0, 0.04)',
    sh2: '0 2px 8px 0 rgba(0, 0, 0, 0.08)',
    sh3: '0 4px 12px 0 rgba(0, 0, 0, 0.10)',
    sh4: '0 8px 24px 0 rgba(0, 0, 0, 0.12)',
    sh5: '0 16px 48px 0 rgba(0, 0, 0, 0.16)',
  },
  motion: {
    ease: {
      standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
      decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
      accelerate: 'cubic-bezier(0.4, 0, 1, 1)',
    },
    duration: {
      instant: '90ms',
      fast: '150ms',
      normal: '240ms',
      slow: '360ms',
      deliberate: '540ms',
    },
  },
  zIndex: {
    base: '0',
    dropdown: '1000',
    sticky: '1100',
    drawer: '1200',
    modal: '1300',
    toast: '1400',
  },
  iconSize: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '20px',
    xl: '24px',
    xxl: '32px',
  },
} as const;

export type Tokens = typeof tokens;
