"""add rum_events table

Revision ID: 0f79be455b42
Revises: 113637cac5d6
Create Date: 2026-08-06 06:46:03.682447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f79be455b42'
down_revision: Union[str, Sequence[str], None] = '113637cac5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rum_events',
    sa.Column('type', sa.String(length=16), nullable=False, comment='perf/error'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='指标/错误名'),
    sa.Column('value', sa.Float(), nullable=True, comment='指标值 ms'),
    sa.Column('rating', sa.String(length=32), nullable=True, comment='good/needs-improvement/poor'),
    sa.Column('message', sa.Text(), nullable=True, comment='错误消息'),
    sa.Column('meta', sa.Text(), nullable=True, comment='附加上下文 JSON'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rum_events')
    # ### end Alembic commands ###
