"""baseline: initial schema

Revision ID: 113637cac5d6
Revises:
Create Date: 2026-08-05 13:15:32.339361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "113637cac5d6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_histories",
        sa.Column("audit_record_id", sa.BigInteger(), nullable=False),
        sa.Column("operator_id", sa.BigInteger(), nullable=False),
        sa.Column("operator_name", sa.String(length=64), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False, comment="approve/revise/reject"),
        sa.Column("comment", sa.String(length=500), nullable=False),
        sa.Column("reject_reason", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_records",
        sa.Column("target_type", sa.String(length=20), nullable=False, comment="novel/chapter"),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False, comment="first/second/final"),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("operator_id", sa.BigInteger(), nullable=False),
        sa.Column("operator_name", sa.String(length=64), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=False),
        sa.Column("reject_reason", sa.String(length=32), nullable=False),
        sa.Column("sensitive_hits", sa.Text(), nullable=False, comment="JSON 快照"),
        sa.Column("submitted_at", sa.BigInteger(), nullable=False),
        sa.Column("processed_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "authors",
        sa.Column("pen_name", sa.String(length=64), nullable=False),
        sa.Column("real_name", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=False),
        sa.Column("contract_type", sa.String(length=20), nullable=False),
        sa.Column("contract_rate", sa.Float(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False, comment="0 待签 1 已签 2 解约"),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "banners",
        sa.Column("book_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("subtitle", sa.String(length=255), nullable=False),
        sa.Column("cover", sa.String(length=255), nullable=False),
        sa.Column("accent", sa.String(length=20), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bookshelves",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("added_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reader_id", "novel_id", name="uq_bookshelf_reader_novel"),
    )
    op.create_table(
        "categories",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("novel_count", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "chapters",
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("pure_word_count", sa.Integer(), nullable=False),
        sa.Column("punctuation_word_count", sa.Integer(), nullable=False),
        sa.Column("is_vip", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("audit_level", sa.String(length=20), nullable=False),
        sa.Column("published_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chapters_novel_index", "chapters", ["novel_id", "index"], unique=True)
    op.create_index("idx_chapters_status", "chapters", ["status", "audit_level"], unique=False)
    op.create_table(
        "comments",
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_id", sa.BigInteger(), nullable=False),
        sa.Column("paragraph_index", sa.Integer(), nullable=False),
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False, comment="1-5，仅书评"),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False, comment="0 待审 1 通过 2 驳回"),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "novels",
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("author_name", sa.String(length=64), nullable=False),
        sa.Column("cover", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("intro", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("flags", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("follow_count", sa.Integer(), nullable=False),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("author_remark", sa.String(length=500), nullable=False),
        sa.Column("published_at", sa.BigInteger(), nullable=False),
        sa.Column("shelved_at", sa.BigInteger(), nullable=False),
        sa.Column("offline_reason", sa.String(length=32), nullable=False),
        sa.Column("offline_remark", sa.String(length=500), nullable=False),
        sa.Column("is_completed", sa.Integer(), nullable=False, comment="0 连载中 1 完结"),
        sa.Column("tags_str", sa.String(length=200), nullable=False, comment="逗号分隔标签"),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_novels_category", "novels", ["category"], unique=False)
    op.create_index("idx_novels_status_updated", "novels", ["status", "updated_at"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("perm_key", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=32), nullable=False),
        sa.Column("module", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("perm_key"),
    )
    op.create_table(
        "reader_notes",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False, comment="选中的原文文本"),
        sa.Column("paragraph_index", sa.Integer(), nullable=False, comment="段落索引"),
        sa.Column("offset_start", sa.Integer(), nullable=False, comment="选中起始位置"),
        sa.Column("offset_end", sa.Integer(), nullable=False, comment="选中结束位置"),
        sa.Column("annotation", sa.Text(), nullable=False, comment="读者笔记内容"),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reader_notes_reader_id"), "reader_notes", ["reader_id"], unique=False)
    op.create_table(
        "readers",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("is_vip", sa.Integer(), nullable=False),
        sa.Column("vip_expire_at", sa.BigInteger(), nullable=False),
        sa.Column("total_reading_minutes", sa.Integer(), nullable=False),
        sa.Column("total_read_words", sa.BigInteger(), nullable=False),
        sa.Column("reading_days", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "reading_histories",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_index", sa.Integer(), nullable=False),
        sa.Column("percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("read_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reader_id", "novel_id", name="uq_history_reader_novel"),
    )
    op.create_index(
        "idx_history_reader_readat", "reading_histories", ["reader_id", "read_at"], unique=False
    )
    op.create_table(
        "reading_stats_daily",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("stat_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("words", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reader_id", "stat_date", name="uq_stats_reader_date"),
    )
    op.create_table(
        "reviews",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("images", sa.String(length=500), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("replies", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reward_records",
        sa.Column("reader_id", sa.BigInteger(), nullable=False),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False, comment="ticket/recommend/tip"),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_key", sa.String(length=32), nullable=False),
        sa.Column("perm_key", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("role_key", "perm_key"),
    )
    op.create_table(
        "roles",
        sa.Column("role_key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("data_scope", sa.String(length=20), nullable=False),
        sa.Column("builtin", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("role_key"),
    )
    op.create_table(
        "royalty_details",
        sa.Column("month", sa.String(length=7), nullable=False, comment="YYYY-MM"),
        sa.Column("novel_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False, comment="含标点字数"),
        sa.Column("contract_type", sa.String(length=20), nullable=False),
        sa.Column("rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("subscription_revenue", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("settled_at", sa.BigInteger(), nullable=False),
        sa.Column("withdrawn_at", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_royalty_details_month"), "royalty_details", ["month"], unique=False)
    op.create_table(
        "sensitive_words",
        sa.Column("text", sa.String(length=64), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False, comment="1 高危 2 警告 3 提示"),
        sa.Column("suggestion", sa.String(length=255), nullable=False),
        sa.Column("lib_version", sa.String(length=20), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text", "level", name="uq_sensitive_text_level"),
    )
    op.create_table(
        "system_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_name", sa.String(length=128), nullable=False),
        sa.Column("icp", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("ref_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tags")
    op.drop_table("system_configs")
    op.drop_table("sensitive_words")
    op.drop_index(op.f("ix_royalty_details_month"), table_name="royalty_details")
    op.drop_table("royalty_details")
    op.drop_table("roles")
    op.drop_table("role_permissions")
    op.drop_table("reward_records")
    op.drop_table("reviews")
    op.drop_table("reading_stats_daily")
    op.drop_index("idx_history_reader_readat", table_name="reading_histories")
    op.drop_table("reading_histories")
    op.drop_table("readers")
    op.drop_index(op.f("ix_reader_notes_reader_id"), table_name="reader_notes")
    op.drop_table("reader_notes")
    op.drop_table("permissions")
    op.drop_index("idx_novels_status_updated", table_name="novels")
    op.drop_index("idx_novels_category", table_name="novels")
    op.drop_table("novels")
    op.drop_table("comments")
    op.drop_index("idx_chapters_status", table_name="chapters")
    op.drop_index("idx_chapters_novel_index", table_name="chapters")
    op.drop_table("chapters")
    op.drop_table("categories")
    op.drop_table("bookshelves")
    op.drop_table("banners")
    op.drop_table("authors")
    op.drop_table("audit_records")
    op.drop_table("audit_histories")
    op.drop_table("admins")
    # ### end Alembic commands ###
